import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApplication} from '../server/app.js';
import {createBackup,restoreBackup} from '../scripts/databaseRecovery.js';

test('combat has one confirmed order with guarded master actions, rounds and membership changes',async()=>{
  const directory=mkdtempSync(join(tmpdir(),'grimorio-combat-')),dbPath=join(directory,'review.sqlite'),cookies={};let app,base,controller;
  async function start(path=dbPath){app=createApplication({dbPath:path,exportRoot:join(directory,'exports'),rateLimit:false,diagnosticsLogger:()=>{}});await new Promise(done=>app.server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${app.server.address().port}/api`;}
  async function stop(){const done=new Promise(resolve=>app.server.once('close',resolve));app.close();app.server.closeAllConnections();await done;app=null;}
  async function call(who,path,method='GET',data){const response=await fetch(base+path,{method,headers:{Cookie:cookies[who]||'',...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(10000)});if(response.headers.has('set-cookie'))cookies[who]=response.headers.get('set-cookie').split(';')[0];return {status:response.status,body:await response.json()};}
  try{
    await start();for(const username of ['owner','master','alice','bob'])await call(username,'/auth/register','POST',{username,password:'local-combat-review'});
    const room=(await call('owner','/rooms','POST',{name:'Ordem de teste'})).body,root='/rooms/'+room.id;
    for(const [username,role]of [['master','master'],['alice','player'],['bob','player']])await call('owner',root+'/members','POST',{username,role});
    let view=(await call('master',root)).body;
    assert.deepEqual(view.state.combat.order,['owner','alice','bob']);
    assert.equal(view.state.combat.schemaVersion,2);assert.equal(view.state.combat.round,0);assert.equal(view.state.combat.activeId,null);
    for(const key of ['turnOrder','turnNpcs','turnExcluded','activePlayer'])assert.equal(Object.hasOwn(view.state,key),false);
    const act=async(action,player,extra={})=>{const result=await call('master',root+'/turns','POST',{action,player,version:view.state.combat.version,...extra});assert.equal(result.status,200,JSON.stringify(result.body));view=result.body;return view.state.combat;};
    assert.equal((await call('alice',root+'/turns','POST',{action:'next',version:view.state.combat.version})).status,403);
    assert.equal((await call('owner',root+'/turns?mapViewMode=player','POST',{action:'next',version:view.state.combat.version})).status,403);
    assert.equal((await call('master',root+'/turns','POST',{action:'next'})).status,400);
    await act('up','bob');assert.deepEqual(view.state.combat.order,['owner','bob','alice']);
    await act('next');assert.equal(view.state.combat.activeId,'owner');assert.equal(view.state.combat.round,1);
    await act('next');assert.equal(view.state.combat.activeId,'bob');
    await act('next');assert.equal(view.state.combat.activeId,'alice');
    await act('next');assert.equal(view.state.combat.activeId,'owner');assert.equal(view.state.combat.round,2);
    await act('remove','owner');assert.equal(view.state.combat.activeId,'bob');assert.equal(view.state.combat.round,2);
    assert.ok(view.members.some(member=>member.username==='owner'));assert.deepEqual(view.state.combat.excluded,['owner']);
    await act('end');assert.equal(view.state.combat.activeId,null);assert.equal(view.state.combat.round,0);
    await act('include','owner');assert.deepEqual(view.state.combat.order,['bob','alice','owner']);
    await act('initiative','bob',{value:20});await act('initiative','alice',{value:20});await act('initiative','owner',{value:5});
    await act('sort');assert.deepEqual(view.state.combat.order,['bob','alice','owner']);
    const unchanged=view.revision;
    await act('sort');assert.equal(view.revision,unchanged);
    for(const value of [1.5,1000,'20'])assert.equal((await call('master',root+'/turns','POST',{action:'initiative',player:'bob',value,version:view.state.combat.version})).status,400);
    assert.equal((await call('master',root+'/turns','POST',{action:'next',round:99,version:view.state.combat.version})).status,400);
    controller=new AbortController();const stream=await fetch(base+root+'/events?mapViewMode=player',{headers:{Cookie:cookies.alice},signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])}),reader=stream.body.getReader(),decoder=new TextDecoder();let buffer='';
    const event=async()=>{while(!buffer.includes('\n\n')){const chunk=await reader.read();assert.equal(chunk.done,false);buffer+=decoder.decode(chunk.value,{stream:true});}const end=buffer.indexOf('\n\n'),frame=buffer.slice(0,end);buffer=buffer.slice(end+2);return JSON.parse(frame.split('data: ')[1]);};
    assert.deepEqual((await event()).state.combat,view.state.combat);
    const version=view.state.combat.version,competing=await Promise.all(['master','owner'].map(who=>call(who,root+'/turns','POST',{action:'next',version})));
    assert.deepEqual(competing.map(result=>result.status).sort(),[200,409]);
    view=competing.find(result=>result.status===200).body;
    assert.equal(view.state.combat.activeId,'bob');assert.equal(view.state.combat.round,1);assert.equal(view.state.combat.version,version+1);
    assert.deepEqual((await event()).state.combat,view.state.combat);
    assert.deepEqual((await call('alice',root)).body.state.combat,view.state.combat);
    const bob=view.members.find(member=>member.username==='bob'),alice=view.members.find(member=>member.username==='alice');
    view=(await call('owner',root+'/members/'+bob.id,'DELETE')).body;
    assert.equal(view.state.combat.activeId,'alice');assert.equal(Object.hasOwn(view.state.combat.initiative,'bob'),false);
    assert.deepEqual((await event()).state.combat,view.state.combat);
    assert.equal((await call('master',root+'/turns','POST',{action:'next',version})).status,409);
    view=(await call('owner',root+'/members/'+alice.id,'PATCH',{role:'master'})).body;
    assert.equal(view.state.combat.activeId,'owner');assert.ok(!view.state.combat.order.includes('alice'));
    view=(await call('owner',root+'/members/'+alice.id,'PATCH',{role:'player'})).body;
    assert.deepEqual(view.state.combat.order,['owner','alice']);assert.equal(view.state.combat.activeId,'owner');
    view=(await call('owner',root+'/members','POST',{username:'bob',role:'player'})).body;
    assert.deepEqual(view.state.combat.order,['owner','alice','bob']);
    controller.abort();
    await act('add',undefined,{name:'Guarda da ponte',kind:'enemy'});const npc=view.state.combat.npcs[0];
    await act('select',npc.id);await act('remove',npc.id);assert.equal(view.state.combat.activeId,'owner');assert.equal(view.state.combat.round,2);
    for(const id of ['owner','alice','bob'])await act('remove',id);
    assert.deepEqual(view.state.combat.order,[]);assert.equal(view.state.combat.activeId,null);assert.equal(view.state.combat.round,0);
    assert.equal((await call('master',root+'/turns','POST',{action:'skip',version:view.state.combat.version})).status,400);
    await call('master',root+'/state','PATCH',{masterNotes:'Texto reservado mantido'});
    view=(await call('master',root+'/tabletop-lighting','PATCH',{preset:'bright',version:view.tabletopLightingVersion})).body;
    const legacyRevision=view.revision;
    await stop();
    const db=new DatabaseSync(dbPath),legacy=JSON.parse(db.prepare('SELECT state FROM rooms WHERE id=?').get(room.id).state);
    legacy.stateVersion=4;delete legacy.combat;legacy.turnOrder=['bob',npc.id,'alice'];legacy.turnNpcs=[npc];legacy.turnExcluded=['owner'];legacy.activePlayer=npc.id;
    db.prepare('UPDATE rooms SET state=? WHERE id=?').run(JSON.stringify(legacy),room.id);db.close();
    await start();view=(await call('master',root)).body;
    assert.equal(view.state.stateVersion,7);assert.equal(view.revision,legacyRevision+1);
    assert.deepEqual(view.state.combat.order,['bob',npc.id,'alice']);assert.deepEqual(view.state.combat.excluded,['owner']);assert.deepEqual(view.state.combat.npcs,[npc]);
    assert.equal(view.state.combat.activeId,npc.id);assert.equal(view.state.combat.round,1);assert.equal(view.state.combat.version,1);
    assert.equal(view.state.tabletopLighting,'bright');assert.equal(view.state.masterNotes,'Texto reservado mantido');
    const migratedRevision=view.revision;
    await stop();await start();view=(await call('master',root)).body;assert.equal(view.revision,migratedRevision);
    const exported=(await call('owner',root+'/exports','POST',{viewMode:'master'})).body,portable=(await call('owner',exported.downloadUrl.replace(/^\/api/,''))).body;
    assert.deepEqual(portable.state.combat,view.state.combat);assert.equal(Object.hasOwn(portable.state,'turnOrder'),false);
    const audit=(await call('owner',root+'/audit?category=turns')).body;
    assert.ok(audit.entries.some(entry=>entry.action==='turns.changed'));
    const backup=join(directory,'combat-backup.sqlite'),restored=join(directory,'restored.sqlite');
    await createBackup(dbPath,backup);await restoreBackup(backup,restored);await stop();await start(restored);
    assert.deepEqual((await call('master',root)).body.state.combat,view.state.combat);
  }finally{controller?.abort();if(app)await stop();assert.ok(resolve(directory).startsWith(resolve(tmpdir())+sep));rmSync(directory,{recursive:true,force:true});}
});
