import {useEffect,useRef,useState} from 'react';
import {defaultMapLegend,isMapLegend,isMapRouteFields,routeDistanceLabel,routePath} from '../shared/mapExploration.js';
import './MapExploration.css';

const count=new Intl.NumberFormat('pt-BR');
export const freshRoute=()=>({id:crypto.randomUUID(),version:null,imageVersion:null,fields:{name:'',color:'#e2c786',status:'planned',visibility:'master',waypoints:[]}});

export default function MapExploration({routes,versions,imageVersion,scale,canManage,draft,onDraft,onChoose,choosing,onStop,onSave,onArchive,busy,hasImage,prefs,onPrefs,error}){
  const [archived,setArchived]=useState(false),[failure,setFailure]=useState(''),failureRef=useRef(null),headingRef=useRef(null),previousChoice=useRef(choosing);
  const current=draft&&routes.find(route=>route.id===draft.id),deleted=draft?.version&&!current;
  const conflict=draft&&(draft.imageVersion!==imageVersion||draft.version!==null&&draft.version!==versions[draft.id]||draft.version===null&&!!current);
  const edit=(key,value)=>{onDraft({...draft,fields:{...draft.fields,[key]:value}});setFailure('');};
  const downloadDraft=()=>{const blob=new Blob([JSON.stringify({format:'grimorio-route-draft',version:1,draft},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='rascunho-rota.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  useEffect(()=>{if(failure)failureRef.current?.focus();},[failure]);
  useEffect(()=>{if(previousChoice.current&&!choosing)headingRef.current?.focus();previousChoice.current=choosing;},[choosing]);
  useEffect(()=>{if(draft?.id&&canManage)headingRef.current?.focus();},[draft?.id]);
  async function save(event){event.preventDefault();if(busy||conflict||deleted)return;const normalized={...draft,fields:{...draft.fields,name:draft.fields.name.trim()}};if(!isMapRouteFields(normalized.fields)){setFailure('Dê um nome à rota e escolha pelo menos dois locais diferentes no mapa.');return;}if(await onSave(normalized))setFailure('');else setFailure('A rota não foi salva. Seus ajustes continuam aqui; confira a conexão e revise a versão da mesa.');}
  const begin=route=>{if(draft){setFailure('Salve ou descarte a rota aberta antes de editar outra.');return;}onDraft(route?{id:route.id,version:versions[route.id],imageVersion,fields:{name:route.name,color:route.color,status:route.status,visibility:route.visibility,waypoints:route.waypoints.map(point=>({...point}))}}:{...freshRoute(),imageVersion});setFailure('');};
  return <fieldset className="map-exploration"><legend>Rotas de exploração</legend>
    <label className="map-exploration-toggle"><input type="checkbox" name="map-show-routes" autoComplete="off" checked={prefs.routes} onChange={event=>onPrefs({...prefs,routes:event.target.checked})}/>Mostrar rotas nesta visão</label>
    <p>Trace um caminho com paradas. A distância soma os trechos; não aplica regras de movimento.</p>
    {canManage&&<><button type="button" disabled={busy||!hasImage||!!draft} onClick={()=>begin(null)}>Nova rota</button><label className="map-exploration-toggle"><input type="checkbox" name="map-show-archived-routes" autoComplete="off" checked={archived} onChange={event=>setArchived(event.target.checked)}/>Ver rotas arquivadas</label></>}
    <ul className="map-route-list">{routes.filter(route=>!!route.archived===(canManage&&archived)).map(route=><li key={route.id}><span><i style={{background:route.color}} aria-hidden="true"/><strong>{route.name}</strong><small>{route.status==='planned'?'Planejada':'Percorrida'} · {routeDistanceLabel(route.waypoints,scale)}{canManage&&route.visibility==='master'?' · Só mestres':''}</small></span>{canManage&&<div><button type="button" disabled={busy||!!draft||route.archived} onClick={()=>begin(route)} aria-label={`Editar rota ${route.name}`}>Editar</button><button type="button" disabled={busy||!!draft} onClick={async()=>{if(!await onArchive(route,!route.archived))setFailure('Não foi possível alterar o arquivo da rota. Confira a versão da mesa.');}} aria-label={`${route.archived?'Restaurar':'Arquivar'} rota ${route.name}`}>{route.archived?'Restaurar':'Arquivar'}</button></div>}</li>)}</ul>
    {!routes.some(route=>!!route.archived===(canManage&&archived))&&<p>{archived?'Nenhuma rota arquivada.':canManage?'Nenhuma rota neste mapa.':'Nenhuma rota compartilhada visível neste mapa.'}</p>}
    {canManage&&draft&&<form className="map-route-editor" onSubmit={save}>
      <h4 id="map-route-editor-title" tabIndex={-1} ref={headingRef}>{draft.version?'Editar rota':'Nova rota'}</h4>
      <label>Nome da rota<input name="map-route-name" autoComplete="off" maxLength={120} value={draft.fields.name} onChange={event=>edit('name',event.target.value)} disabled={busy} required placeholder="Ex.: Caminho até o porto…"/></label>
      <label>Cor da rota<input type="color" name="map-route-color" autoComplete="off" value={draft.fields.color} onInput={event=>edit('color',event.target.value)} onChange={event=>edit('color',event.target.value)} disabled={busy}/></label>
      <label>Estado da rota<select name="map-route-status" autoComplete="off" value={draft.fields.status} onChange={event=>edit('status',event.target.value)} disabled={busy}><option value="planned">Planejada · linha tracejada</option><option value="traveled">Percorrida · linha contínua</option></select></label>
      <label>Quem pode ver a rota<select name="map-route-visibility" autoComplete="off" value={draft.fields.visibility} onChange={event=>edit('visibility',event.target.value)} disabled={busy}><option value="master">Só mestres</option><option value="table">Compartilhada com a mesa</option></select></label>
      <p>{count.format(draft.fields.waypoints.length)} paradas · {routeDistanceLabel(draft.fields.waypoints,scale)}. Até 100 paradas por rota.</p>
      <button type="button" disabled={busy||conflict||deleted||draft.fields.waypoints.length>=100} onClick={onChoose}>{choosing?'Continuar escolhendo no mapa':'Escolher paradas no mapa'}</button>
      {choosing&&<button type="button" onClick={onStop}>Voltar aos detalhes da rota</button>}
      <p>Clique ou toque para adicionar uma parada. Pelo teclado, Enter marca, setas movem e Escape volta aos detalhes. A prévia só é publicada ao salvar.</p>
      {!!draft.fields.waypoints.length&&<button type="button" disabled={busy} onClick={()=>edit('waypoints',draft.fields.waypoints.slice(0,-1))}>Remover última parada</button>}
      {conflict&&<div className="map-exploration-error" role="alert"><p>{draft.imageVersion!==imageVersion?'A imagem mudou. Seus dados foram mantidos; desenhe novamente o caminho no mapa atual.':deleted?'Esta rota foi removida do mapa. Seus dados continuam disponíveis para copiar.':'A rota mudou em outra tela. Confira a versão atual antes de salvar seus ajustes.'}</p>{(!deleted||draft.imageVersion!==imageVersion)&&<button type="button" disabled={busy} onClick={()=>{onDraft({...draft,id:draft.imageVersion!==imageVersion?crypto.randomUUID():draft.id,version:draft.imageVersion!==imageVersion?null:current?versions[current.id]:null,imageVersion,fields:draft.imageVersion!==imageVersion?{...draft.fields,waypoints:[]}:draft.fields});setFailure('');}}>Manter ajustes e revisar no mapa atual</button>}{current&&<p>Na mesa: {current.name} · {current.status==='planned'?'Planejada':'Percorrida'} · {current.visibility==='master'?'Só mestres':'Compartilhada'} · {count.format(current.waypoints.length)} paradas.</p>}</div>}
      <button type="submit" disabled={busy||conflict||deleted}>{busy?'Salvando…':'Salvar rota na mesa'}</button>
      <button type="button" onClick={downloadDraft}>Baixar cópia do rascunho da rota</button>
      <details><summary>Descartar esta edição</summary><p>O rascunho desta rota será descartado. A versão salva na mesa permanece.</p><button type="button" disabled={busy} onClick={()=>{onStop();onDraft(null);setFailure('');}}>Descartar rascunho da rota</button></details>
    </form>}
    {failure&&<p ref={failureRef} tabIndex={-1} role="alert" className="map-exploration-error">{failure}{error&&` ${error}`}</p>}
  </fieldset>;
}

export function MapLegendEditor({legend,version,canManage,onSave,busy,prefs,onPrefs,draft,onDraft:setDraft}){
  const [failure,setFailure]=useState(''),failureRef=useRef(null),values=draft?.values||legend,conflict=draft&&draft.version!==version;
  useEffect(()=>{if(failure)failureRef.current?.focus();},[failure]);
  const edit=(index,key,value)=>{setDraft({version:draft?.version||version,values:values.map((entry,i)=>i===index?{...entry,[key]:value}:entry)});setFailure('');};
  async function save(event){event.preventDefault();const next=values.map(entry=>({...entry,label:entry.label.trim()}));if(conflict||busy)return;if(!isMapLegend(next)){setFailure('Use nomes de 1 a 40 caracteres e cores válidas para os cinco tipos.');return;}if(await onSave(next,draft?.version||version)){setDraft(null);setFailure('');}else setFailure('A legenda não foi salva. Seus ajustes continuam aqui.');}
  return <fieldset className="map-exploration"><legend>Legenda do mapa</legend><label className="map-exploration-toggle"><input type="checkbox" name="map-show-legend" autoComplete="off" checked={prefs.legend} onChange={event=>onPrefs({...prefs,legend:event.target.checked})}/>Mostrar legenda nesta visão</label>
    {canManage?<details><summary>Editar nomes e cores</summary><form onSubmit={save} className="map-legend-editor"><p>Os cinco tipos continuam ligados aos mesmos pontos. Os nomes e cores são compartilhados com a mesa.</p>{values.map((entry,index)=><div key={entry.type}><label>Nome de {defaultMapLegend()[index].label}<input name={`map-legend-label-${entry.type}`} autoComplete="off" value={entry.label} maxLength={40} required disabled={busy} onChange={event=>edit(index,'label',event.target.value)}/></label><label>Cor de {defaultMapLegend()[index].label}<input type="color" name={`map-legend-color-${entry.type}`} autoComplete="off" value={entry.color} disabled={busy} onInput={event=>edit(index,'color',event.target.value)} onChange={event=>edit(index,'color',event.target.value)}/></label></div>)}{conflict&&<div className="map-exploration-error" role="alert"><p>A legenda mudou na mesa. Seus ajustes foram preservados.</p><button type="button" onClick={()=>setDraft(null)}>Usar legenda atual</button><button type="button" onClick={()=>setDraft({...draft,version})}>Manter meus ajustes</button></div>}{failure&&<p ref={failureRef} tabIndex={-1} role="alert" className="map-exploration-error">{failure}</p>}<button type="submit" disabled={busy||conflict}>{busy?'Salvando…':'Salvar legenda na mesa'}</button>{draft&&<button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancelar ajustes da legenda</button>}</form></details>:<p>Os nomes e cores são definidos pelo mestre.</p>}
  </fieldset>;
}

export function MapRouteOverlay({routes,draft,cursor,screenRatio,scale}){
  const unit=1/Math.max(.001,screenRatio);
  return <g className="map-routes">{routes.filter(route=>!route.archived).map((route,index)=><g key={route.id} data-route-id={route.id}><path d={routePath(route.waypoints)} fill="none" stroke={route.color} strokeWidth={4*unit} strokeDasharray={route.status==='planned'?`${9*unit} ${6*unit}`:undefined} strokeLinecap="round" strokeLinejoin="round"/><text x={route.waypoints.at(-1).x} y={route.waypoints.at(-1).y+(22+index%5*18)*unit} textAnchor="middle" fontSize={13*unit} fill="#fff1cf" stroke="#151913" strokeWidth={3*unit} paintOrder="stroke">{route.name.length>32?route.name.slice(0,31)+'…':route.name} · {routeDistanceLabel(route.waypoints,scale)}</text></g>)}{draft&&<g><path d={routePath(draft.fields.waypoints)} fill="none" stroke={draft.fields.color} strokeWidth={3*unit} strokeDasharray={`${5*unit} ${4*unit}`}/>{draft.fields.waypoints.map((point,index)=><g key={index}><circle cx={point.x} cy={point.y} r={8*unit} fill={draft.fields.color} stroke="#151913" strokeWidth={2*unit}/><text x={point.x} y={point.y+4*unit} textAnchor="middle" fill="#151913" fontSize={11*unit}>{index+1}</text></g>)}{cursor&&<circle cx={cursor.x} cy={cursor.y} r={11*unit} fill="none" stroke="#fff1cf" strokeWidth={2*unit}/>}</g>}</g>;
}

export function MapLegend({legend}){return <aside className="map-view-legend" aria-label="Legenda da vista"><h3>Legenda</h3><ul>{legend.map(entry=><li key={entry.type}><span style={{background:entry.color}} aria-hidden="true"/>{entry.label}</li>)}</ul></aside>;}
